import type { CanvasClipboard, CanvasConnection, CanvasConnectionDropResult, CanvasConnectionDropTarget, CanvasDocument, CanvasInteractionState, CanvasNode, CanvasNodeDragResult, CanvasRect, CanvasSelection, ConnectionHandle, Position, ViewportTransform } from "./model";

export type ViewportUpdater = ViewportTransform | ((viewport: ViewportTransform) => ViewportTransform);
export type CanvasNodePatch<TMetadata = unknown> = Partial<CanvasNode<TMetadata>> | ((node: CanvasNode<TMetadata>) => CanvasNode<TMetadata>);
export type CanvasDocumentUpdater<TMetadata = unknown> = (document: CanvasDocument<TMetadata>) => CanvasDocument<TMetadata>;
export type CanvasPasteOptions<TMetadata = unknown> = {
    position: Position;
    createNodeId: (node: CanvasNode<TMetadata>, index: number) => string;
    createConnectionId: (connection: CanvasConnection, index: number) => string;
    mapNode?: (node: CanvasNode<TMetadata>, index: number) => CanvasNode<TMetadata>;
};
export type CanvasCommands<TMetadata = unknown> = {
    setDocument: (document: CanvasDocument<TMetadata>) => void;
    addNode: (node: CanvasNode<TMetadata>) => CanvasDocument<TMetadata>;
    addNodes: (nodes: CanvasNode<TMetadata>[]) => CanvasDocument<TMetadata>;
    updateNode: (id: string, patch: CanvasNodePatch<TMetadata>) => CanvasDocument<TMetadata>;
    removeNodes: (ids: Iterable<string>) => CanvasDocument<TMetadata>;
    addConnection: (connection: CanvasConnection) => CanvasDocument<TMetadata>;
    addConnections: (connections: CanvasConnection[]) => CanvasDocument<TMetadata>;
    removeConnections: (ids: Iterable<string>) => CanvasDocument<TMetadata>;
    selectNodes: (ids: Iterable<string>) => void;
    selectNodesInRect: (rect: CanvasRect, initialIds?: Iterable<string>) => ReadonlySet<string>;
    selectConnection: (id: string | null) => void;
    clearSelection: () => void;
    startNodeDrag: (ids: Iterable<string>, pointer: Position) => void;
    moveNodeDrag: (pointer: Position) => string | null;
    endNodeDrag: (pointer?: Position) => CanvasNodeDragResult;
    startNodeResize: (id: string) => void;
    resizeNode: (id: string, width: number, height: number, position?: Position) => CanvasDocument<TMetadata>;
    endNodeResize: () => void;
    cancelNodeResize: () => void;
    startConnection: (handle: ConnectionHandle, position: Position) => void;
    moveConnection: (position: Position) => CanvasConnectionDropTarget | null;
    endConnection: (position: Position) => CanvasConnectionDropResult | null;
    cancelConnection: () => void;
    copySelection: () => CanvasClipboard<TMetadata> | null;
    pasteClipboard: (options: CanvasPasteOptions<TMetadata>) => CanvasClipboard<TMetadata> | null;
    getClipboard: () => CanvasClipboard<TMetadata> | null;
    getDocument: () => CanvasDocument<TMetadata>;
    getViewport: () => ViewportTransform;
    getSelection: () => CanvasSelection;
    getInteraction: () => CanvasInteractionState;
    getHistoryDocuments: () => CanvasDocument<TMetadata>[];
    transaction: (updater: CanvasDocumentUpdater<TMetadata>) => CanvasDocument<TMetadata>;
    setViewport: (updater: ViewportUpdater) => ViewportTransform;
    undo: () => void;
    redo: () => void;
    preview: (updater: CanvasDocumentUpdater<TMetadata>) => CanvasDocument<TMetadata>;
    commitPreview: () => void;
    cancelPreview: () => void;
};
