export type Position = { x: number; y: number };
export type CanvasSize = { width: number; height: number };
export type ViewportTransform = Position & { k: number };
export type CanvasRect = Position & CanvasSize;
export type CanvasTool = "select" | "pan";
export type CanvasResizeCorner = "top-left" | "top-right" | "bottom-left" | "bottom-right";
export type CanvasNodeTypeId = string;
export type CanvasNodeRole = "group";
export type CanvasNode<TMetadata = unknown> = {
    id: string;
    type: CanvasNodeTypeId;
    role?: CanvasNodeRole;
    groupId?: string;
    title: string;
    position: Position;
    width: number;
    height: number;
    metadata?: TMetadata;
};
export type CanvasConnection = { id: string; fromNodeId: string; toNodeId: string };
export type CanvasDocument<TMetadata = unknown> = { nodes: CanvasNode<TMetadata>[]; connections: CanvasConnection[] };
export type CanvasClipboard<TMetadata = unknown> = CanvasDocument<TMetadata>;
export type CanvasSelection = { nodeIds: ReadonlySet<string>; connectionId: string | null };
export type CanvasConnectionResolver<TMetadata = unknown> = (first: CanvasNode<TMetadata>, second: CanvasNode<TMetadata>, firstHandleType: "source" | "target") => Omit<CanvasConnection, "id"> | null;
export type CanvasGroupResolver<TMetadata = unknown> = (node: CanvasNode<TMetadata>, group: CanvasNode<TMetadata>) => boolean;
export type ConnectionHandle = { nodeId: string; handleType: "source" | "target" };
export type CanvasConnectionInteraction = { handle: ConnectionHandle; pointer: Position; targetNodeId: string | null };
export type CanvasConnectionDropTarget = { nodeId: string | null; isNearNode: boolean };
export type CanvasConnectionDropResult = CanvasConnectionDropTarget & { handle: ConnectionHandle; position: Position; connection: Omit<CanvasConnection, "id"> | null };
export type CanvasInteractionState = { isNodeDragging: boolean; isNodeResizing: boolean; dropTargetGroupId: string | null; connectionInteraction: CanvasConnectionInteraction | null };
export type CanvasNodeDragResult = { moved: boolean; clickedNodeId: string | null };
export type CanvasShortcut = "undo" | "redo" | "select-all" | "copy" | "paste" | "delete" | "escape";
